six-group/six-webcomponents

.github/workflows/publish.yml
lerna.json
source/packages/ui-library-react/package-lock.json
source/packages/ui-library-react/package.json
source/packages/ui-library-vue/package-lock.json
source/packages/ui-library-vue/package.json
source/packages/ui-library/package-lock.json
source/packages/ui-library/package.json

Release 3.0.0 beta.1.12

---

.idea/six-webcomponents.iml
libraries/ui-library/src/components.d.ts
libraries/ui-library/src/components/six-select/readme.md
libraries/ui-library/src/components/six-select/six-select.tsx
libraries/ui-library/src/components/six-select/test/util.spec.ts
libraries/ui-library/src/components/six-select/util.ts

* Ensures that the `value` property will either return a string or a string array (never undefined or null)
* Resolved eslint warnings
* Strict typing

Strict typing for six-select

---

libraries/ui-library/src/components/six-button/six-button.tsx

fix: duplicated click event on button

---

examples/react/src/components/App.tsx
libraries/ui-library/package.json
libraries/ui-library/src/components/six-item-picker/six-item-picker.tsx
libraries/ui-library/src/utils/event-listeners.ts
package-lock.json

Upgraded stencil libs to v4. Some other minor fixes were required, but no breaking changes luckily. Implements #69

Upgraded libs (Implements #69)

---

libraries/ui-library/src/components/six-input/six-input.scss

`six-input` and `six-datepicker` were not resizing their input text based on the `size` property provided.

size input/datepicker based on size property (fixes #55)

---

docs/scripts/components.mjs

After having a few issues due to a malformed index.html file in one component, I added a more descriptive error message so hopefully whoever stumbles on the same problem can resolve it quickly

Improve message on docs error

---

README.md

fix: update broken reference to changelog in docs

---

docs/components/six-details.md
libraries/ui-library/src/components/six-details/readme.md
libraries/ui-library/src/components/six-details/six-details.scss
libraries/ui-library/src/components/six-sidebar-item-group/six-sidebar-item-group.scss
libraries/ui-library/src/components/six-sidebar-item-group/six-sidebar-item-group.tsx
libraries/ui-library/src/components/six-sidebar-item-group/test/six-sidebar-item-group.spec.tsx
libraries/ui-library/src/components/six-sidebar/six-sidebar.scss

fix horizontal gap in six-sidebar-item-group

---

.idea/misc.xml
.idea/runConfigurations/build.xml
.idea/runConfigurations/build_lib.xml
.idea/runConfigurations/demo_angular.xml
.idea/runConfigurations/demo_react.xml
.idea/runConfigurations/watch_angular.xml
docs/guide/readme.md
libraries/ui-library/package.json
libraries/ui-library/src/components/six-button/six-button.tsx
package.json

Prevent click event if button is disabled

---

docs/changelog.md

chore: update changelog

---

docs/components/six-datepicker.md
docs/examples/docs-demo-six-datepicker-22.vue
libraries/ui-library/src/components/six-datepicker/index.html

Bugfix for fixing issue 116 datepicker modal demo not working properly

---

docs/guide/readme.md

Fix typo in the documentation

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.MD

chore: update pull request and bug report templates

---

docs/changelog.md
docs/guide/readme.md
examples/angular/src/app/components/left-sidebar/left-sidebar.component.html
examples/angular/src/app/pages/form/form.component.html
examples/angular/src/app/pages/form/form.component.scss
examples/angular/src/app/pages/form/form.component.ts
libraries/ui-library-angular/src/lib/validators/six-ui-library-validators.ts

Fixed Angular validators for `six-datepicker`

fix: date validators for six-datepicker

---

docs/changelog.md

chore: update changelog for latest release v4.0.4

---

.github/PULL_REQUEST_TEMPLATE.MD
docs/changelog.md

chore: update pull request template with changelog entry

---

docs/.vitepress/config.mts
docs/guide/tables.md

Document AG Grid table style

---

docs/changelog.md
libraries/ui-library/src/components/six-header/six-header.tsx
libraries/ui-library/src/components/six-header/test/six-header.spec.tsx

Fix #153: Show the correct active app in six-header

---

docs/changelog.md
libraries/ui-library/src/components/six-icon/six-icon.scss

fix: [#166] Icons names could be selected by the users

---

docs/changelog.md
libraries/ui-library/src/components/six-icon/six-icon.scss

Before:
After:
Proof that it is centered:

fix: [#165]  Slot of six-icon was not centered

---

docs/changelog.md

Fix changelog formatting mistakes

---

docs/changelog.md
docs/components/six-spinner.md
docs/examples/docs-demo-six-spinner-1.vue
libraries/ui-library/src/components/six-spinner/index.html
libraries/ui-library/src/components/six-spinner/readme.md
libraries/ui-library/src/components/six-spinner/six-spinner.tsx
libraries/ui-library/src/components/six-spinner/test/six-spinner.spec.tsx

Resolves #163 
Introduced part attribute to svg in six-spinner so user can style the six-logo styled spinner.

fix: [#163] added part to svg so users can also resize the six logo spinner

---

docs/changelog.md
docs/components/six-header.md
libraries/ui-library-angular/src/lib/stencil-generated/components.ts
libraries/ui-library-vue/src/lib/stencil-generated/components.ts
libraries/ui-library/src/components.d.ts
libraries/ui-library/src/components/six-header/readme.md
libraries/ui-library/src/components/six-header/six-header.tsx
libraries/ui-library/src/components/six-header/test/six-header.spec.tsx

See #157 
- [] 👌 Enhancement (improving an existing functionality like performance)

Allow to hide the hamburger menu in six-header, closes #157

---

docs/changelog.md
docs/guide/readme.md
docs/guide/vue.md
docs/index.md
docs/package.json
examples/vue/package.json
examples/vue/src/main.ts
examples/vue/vite.config.ts
libraries/ui-library-vue/src/lib/plugin.ts

Setup the deployment of the Vue demo app and add documentation for the Vue library.
This PR also includes a small bug fix: It fixes an issue where the Vue plugin throws an error if no options are provided during registration. Additionally, it renames the Vue plugin to `UiLibraryVue` for better consistency with the Angular version.
The upcoming section now also describes Vue support no longer as "experimental", as I believe it is stable enough now that v-model and the router is working as expected.

Vue Support: Setup deployment of Vue example app and add Vue docs

---

docs/.vitepress/config.mts

Add missing link to Vue docs in left side navi.

Add missing link to Vue docs

---

libraries/ui-library/src/components/six-file-upload/six-file-upload.scss

fix #173: remove unused kyc scss class

---

libraries/ui-library/src/components/six-button/six-button.scss
libraries/ui-library/src/components/six-file-list-item/six-file-list-item.scss
libraries/ui-library/src/components/six-file-upload/six-file-upload.scss
libraries/ui-library/src/components/six-icon/six-icon.scss

fix icon alignment problems introduced with pr #168

---

README.md

Updated readme to be on the newest state

---

docs/changelog.md
docs/components/six-alert.md
docs/examples/docs-demo-six-alert-6.vue
examples/angular/src/app/app.module.ts
examples/angular/src/app/app.routes.ts
examples/angular/src/app/components/left-sidebar/left-sidebar.component.html
examples/angular/src/app/pages/alert/alert.component.html
examples/angular/src/app/pages/alert/alert.component.scss
examples/angular/src/app/pages/alert/alert.component.ts
examples/vue/src/main.css
examples/vue/src/views/AlertView.vue
libraries/ui-library-angular/src/lib/services/alert.service.ts
libraries/ui-library-angular/src/public-api.ts
libraries/ui-library/src/components.d.ts
libraries/ui-library/src/components/six-alert/index.html
libraries/ui-library/src/components/six-alert/readme.md
libraries/ui-library/src/components/six-alert/six-alert.scss
libraries/ui-library/src/components/six-alert/six-alert.tsx
libraries/ui-library/src/global/base.css
libraries/ui-library/src/index.ts
libraries/ui-library/src/types.d.ts
libraries/ui-library/src/utils/alert.ts
package.json

- toast alert utilities for Angular and Vue
- add box shadow if displayed as toast
- adjust top spacing to six-root header slot
- examle for toast alerts in Angular and Vue examples

feat: toast alert utils for Angular and Vue

---

docs/changelog.md
libraries/ui-library/src/components/six-details/six-details.scss
libraries/ui-library/src/global/base.css

The CSS variable `--six-details-color` has been correctly updated since it's only used for this component. The hover color change code has been removed.
Resolves #180 

fix #180: text color change in six-details is not affected by hover

---

README.md

fix third-party-license link in the readme

---

examples/angular/src/app/app.module.ts
examples/angular/src/app/app.routes.ts
examples/angular/src/app/components/left-sidebar/left-sidebar.component.html
examples/angular/src/app/pages/dialog/dialog.component.html
examples/angular/src/app/pages/dialog/dialog.component.scss
examples/angular/src/app/pages/dialog/dialog.component.ts

chore: add angular dialog example

---

docs/changelog.md
docs/components/six-alert.md
libraries/ui-library/src/components.d.ts
libraries/ui-library/src/components/six-alert/readme.md
libraries/ui-library/src/components/six-alert/six-alert.tsx

#184 
`six-alert` when used as a toast in combination with a duration does now stay open indefinitely when hovered. Previously discussed in the web-components weekly with the team.

Pause timer on mouse enter and reset timer on mouse leave.

---

docs/changelog.md
libraries/ui-library/src/components/six-tab-group/six-tab-group.tsx

#215 
This enhancement improves the look and feel of the six-tab-group scroll controls.

six-tab-group added conditional logic to right/left navigation arrows.

---

docs/changelog.md
libraries/ui-library/src/components/six-range/six-range.scss
libraries/ui-library/src/components/six-range/six-range.tsx

fix #191: label of six-range being misaligned

---

docs/changelog.md
libraries/ui-library/src/components/six-language-switcher/six-language-switcher.scss
libraries/ui-library/src/components/six-language-switcher/six-language-switcher.tsx
libraries/ui-library/src/components/six-language-switcher/test/six-language-switcher.spec.tsx

feat: change look and feel for language-switcher #219

---

docs/changelog.md
libraries/ui-library/package.json
package-lock.json

Upgrade stencil minor version and jest to major version 29

---

docs/changelog.md

docs: update changelog for release

---

docs/changelog.md
libraries/ui-library/src/components/six-checkbox/six-checkbox.scss

#218 
Resolves #218
six-checkbox now stays in the correct square shape if there the content spans over multiple lines.

Fix #218 six-checkbox being distorted with multiline text/content

---

docs/changelog.md
libraries/ui-library/src/components/six-sidebar-item-group/six-sidebar-item-group.scss

#192 
The text will now overflow in the sidebar when it reaches the border. I did not want to extend the sidebar, this would lead to some quite large sidebars that look weird in my opinion.
Chat me up if you want to talk about that :)

Fix #192 six-sidebar text overflow

---

package-lock.json

Vulernabilities according to Github Dependabot
Before: 6 vulnerabilities (4 moderate, 2 high)
After: found 0 vulnerabilities

chore: address vulnerabilities in dependencies

---

.github/release.md
docs/guide/release.md

Documented the steps required to perform a release. Very early draft, feel free to modify at will!

Release Docs

---

docs/README.md
docs/changelog.md
docs/components/six-error.md
libraries/ui-library/src/components/six-error/readme.md

Fix six error examples not showing because of the readme template

---

docs/changelog.md
libraries/ui-library/src/components/six-select/six-select.tsx

fix: fire blur event when leaving multiselect

---

docs/changelog.md
libraries/ui-library/src/components/six-datepicker/six-datepicker.tsx

fix: apply the debounce property from the date-picker to the time-picker

---

.github/contributing.md

Correct test and project structure section in the contributing docs

---

docs/changelog.md
libraries/ui-library/src/components/six-datepicker/six-datepicker.tsx

fix: wrong value in datepicker on immediate blur

---

docs/changelog.md

docs: Update changelog for 4.2.3 release

---

libraries/ui-library/src/components/six-error/six-error.scss

https://github.com/six-group/six-webcomponents/issues/247
Sets a font-size on the element

fix #247: Add font-size to six-error

---

docs/changelog.md

Changelog preparation for release 4.2.4

docs: Update changelog for 4.2.4 release

---

libraries/ui-library/src/components/six-file-upload/six-file-upload.tsx

None
Removed leftover console.log statement

Removed console log statements

---

docs/.vitepress/config.mts
docs/.vitepress/theme/index.ts
docs/.vitepress/theme/style.css
docs/package.json
package-lock.json

Upgrading Vitepress to the first major release and fix import.meta.glob issue: https://github.com/vitejs/vite/discussions/7066

chore: upgrade vitepress dependency to stable release and adjust configuration

---

docs/changelog.md
libraries/ui-library/src/components/six-menu/six-menu.tsx
libraries/ui-library/src/components/six-menu/test/six-menu.spec.tsx

fix #257 last item gets partially cut off when using virtual-scroll

---

docs/changelog.md
docs/components/six-input.md
libraries/ui-library-angular/src/lib/stencil-generated/components.ts
libraries/ui-library/src/components.d.ts
libraries/ui-library/src/components/six-input/readme.md
libraries/ui-library/src/components/six-input/six-input.tsx

Resolves #288 by adding a getter method for the selection range on six input

fix #288: Add getter for selection range

---

docs/changelog.md

Changelog preparation for release 4.2.5

docs: Update changelog for 4.2.5 release

---

package-lock.json

chore: fix security issue inside lib packages with high severity

---

package-lock.json

chore: fix moderate security vulnerabilities

---

docs/changelog.md

chore: prepare release 4.2.6

---

.github/workflows/ci.yml
.github/workflows/insider-release.yml
.github/workflows/release.yml

chore: update github actions to v4

---

docs/changelog.md
libraries/ui-library/src/components/six-file-upload/six-file-upload.tsx

When a file is dropped in the drop area, handleFiles is currently being called twice (from both `dropHandler` and `onChange`). Since handleFiles is already being called in the onChange handler, it’s redundant to call it in the dropHandler as well.

fix handleFiles is called twice

---

docs/changelog.md

docs: Update changelog for 4.3.0 release

---

docs/components/six-alert.md
docs/examples/docs-demo-six-alert-7.vue
libraries/ui-library/src/components/six-alert/index.html

#170 implement toast stack example

---

package-lock.json

fix: resolve fixable security vulnerabilities

---

docs/changelog.md

Changelog preparation for release 4.3.1

docs: Update changelog for 4.3.1 release

---

.github/release.md
.github/workflows/insider-release.yml
.github/workflows/release.yml
.github/workflows/variables.yml

Support Patch Releases

---

package-lock.json

chore: update dependencies for fixable securtiy vulnerabilities

---

docs/changelog.md
libraries/ui-library/src/components/six-timepicker/six-timepicker.scss

Fix #343: Remove unnecessary bottom padding on timepicker

---

docs/changelog.md
libraries/ui-library-react/package.json
libraries/ui-library-react/src/lib/stencil-generated/components.ts
libraries/ui-library/package.json
package-lock.json

feat: update react output target to major release v1

---

docs/changelog.md
libraries/ui-library-angular/src/lib/stencil-generated/components.ts
libraries/ui-library/package.json
package-lock.json

chore: update angular output target

---

examples/angular/angular.json
libraries/ui-library-react/package.json
libraries/ui-library/package.json
libraries/ui-library/src/components.d.ts
package-lock.json

chore: update stencil packages and audit findings

---

examples/vue/package.json
package-lock.json
package.json

No real breaking changes except deprecation of old Nodejs versions

chore: update npm run all2 to latest major

---

README.md

docs: add npm latest tags to readme
